# Generated by Django 3.0.5 on 2020-05-05 17:41

from django.db import migrations
import emotion.managers


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', emotion.managers.CustomUserManager()),
            ],
        ),
    ]
