# Generated by Django 3.0.5 on 2020-05-02 18:23

from django.db import migrations
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
    ]
